// Generated by Supabase MCP on December 22, 2025
// This file contains properly generated TypeScript types from the actual database schema
//
// ═══════════════════════════════════════════════════════════════════════════
// 🎯 MIGRATION WORKFLOW (PRODUCTION ONLY - NO SUBSQUID YET)
// ═══════════════════════════════════════════════════════════════════════════
//
// CURRENT STATUS (Dec 25, 2025):
// ✅ Production: Supabase database + API routes (LIVE)
// ⏸️ Development: Subsquid indexer (localhost testing only)
// 🎯 Future: Move Subsquid to production after all migrations + page audits complete
//
// HOW TO APPLY MIGRATIONS:
// 1. Create migration SQL file: supabase/migrations/YYYYMMDDHHMMSS_description.sql
// 2. Apply via Supabase MCP: mcp_supabase_apply_migration(name, query)
// 3. Verify schema: mcp_supabase_list_tables(['public'])
// 4. Update this file MANUALLY (see "Manual Type Updates" below)
//
// ❌ FORBIDDEN:
// - NEVER run: npx supabase gen types typescript
// - NEVER regenerate this file from scratch
// - NEVER use auto-generation tools
//
// ✅ REQUIRED:
// - Use mcp_supabase_apply_migration for all schema changes
// - Manually add new tables/columns to this file
// - Preserve existing type definitions (don't overwrite)
// - Insert new tables alphabetically in Tables section
//
// ═══════════════════════════════════════════════════════════════════════════
// 📝 MANUAL TYPE UPDATES (After MCP Migration)
// ═══════════════════════════════════════════════════════════════════════════
//
// After applying migration via MCP:
// 1. Find table definition in this file (use Cmd/Ctrl+F)
// 2. Add new columns to 3 places:
//    - Row: { column_name: type } - Full row from database
//    - Insert: { column_name?: type } - Optional if has default value
//    - Update: { column_name?: type } - Always optional
// 3. Match Supabase types: TEXT→string, INTEGER→number, BOOLEAN→boolean, etc.
// 4. Document change in "Manual additions" section below
//
// EXAMPLE (adding a column):
// some_table: {
//   Row: {
//     new_column: string  // ← Add here (NOT NULL → required)
//   }
//   Insert: {
//     new_column?: string  // ← Add here (has DEFAULT → optional)
//   }
//   Update: {
//     new_column?: string  // ← Add here (always optional)
//   }
// }
//
// Manual additions:
// - 2025-12-21: reward_claims - Reward claim tracking table
// - 2026-01-09: guild_off_chain_metadata - Renamed from guild_metadata (off-chain fields only)
//
// Tables removed (2026-01-09):
// - guild_analytics_cache - Redundant with Subsquid indexer
// - guild_member_stats_cache - Redundant with Subsquid indexer
// - guild_stats_cache - Redundant with Subsquid indexer
// - 2025-12-28: unified_quests.verification_data - Populated 'type' field within JSONB (Bug #21 fix)
//               Migration: 20251228000000_populate_verification_data_type.sql
//               Note: No schema changes - only data population within existing JSONB column
//
// ═══════════════════════════════════════════════════════════════════════════
// 🎯 POINTS NAMING CONVENTION (Contract = Source of Truth)
// ═══════════════════════════════════════════════════════════════════════════
//
// MIGRATION UPDATE (2025-12-22): All column names updated to match contract naming
// See: POINTS-NAMING-CONVENTION.md, MULTI-WALLET-CACHE-ARCHITECTURE.md
//
// RULE: Contract names are immutable source of truth
// - Contract: pointsBalance, pointsEarned, treasuryPoints (camelCase)
// - Subsquid: pointsBalance, pointsEarned, treasuryPoints (camelCase - exact match)
// - Supabase: points_balance, points_earned, treasury_points (snake_case)
// - API: pointsBalance, pointsEarned, treasuryPoints (camelCase)
//
// Renamed columns:
// - user_profiles: points→points_balance, total_points_earned→total_earned_from_gms, xp dropped
// - badge_casts: viral_bonus_points→viral_bonus_xp (Dec 27 fix)
// - quest_definitions: reward_xp→reward_points_awarded
// - unified_quests: reward_points→reward_points_awarded, total_earned_points→total_points_awarded
// - user_points_balances: base_points→points_balance, viral_points→viral_xp (Dec 27 fix), guild_bonus→guild_points_awarded, total_points→total_score
// - reward_claims: viral_xp_claimed→viral_points_claimed, guild_bonus_claimed→guild_points_claimed, total_claimed→total_points_claimed
// - referral_stats: points_earned→points_awarded
// - points_transactions: balance_after→points_balance_after
//
// ❌ FORBIDDEN: "blockchainPoints" (→ pointsBalance), "base_points" (→ points_balance), "total_points" (→ total_score)
// ✅ CORRECT: "viralXP" / "viral_xp" (progression system, separate from Points currency)
// ℹ️ NOTE: XP (progression/leveling) ≠ Points (spendable currency) - two separate reward systems
//   - Viral XP: Quest unlock requirement (min_viral_xp_required), progression metric
//   - Contract Points: Quest rewards (reward_points_awarded), spendable currency
// ✅ REQUIRED: Update all 4 layers (Contract → Subsquid → Supabase → API)
//
// ═══════════════════════════════════════════════════════════════════════════
// 📦 RPC FUNCTIONS & CUSTOM TYPES
// ═══════════════════════════════════════════════════════════════════════════
//
// RPC FUNCTIONS UPDATE (2025-12-24):
// - 2025-12-24: get_guild_stats_atomic - Atomic guild stats calculation (BUG #2 fix)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      badge_casts: {
        Row: {
          badge_id: string
          cast_hash: string
          cast_url: string
          created_at: string
          fid: number
          id: string
          last_metrics_update: string | null
          likes_count: number | null
          recasts_count: number | null
          replies_count: number | null
          tier: string
          viral_bonus_xp: number | null
          viral_score: number | null
          viral_tier: string | null
        }
        Insert: {
          badge_id: string
          cast_hash: string
          cast_url: string
          created_at?: string
          fid: number
          id?: string
          last_metrics_update?: string | null
          likes_count?: number | null
          recasts_count?: number | null
          replies_count?: number | null
          tier: string
          viral_bonus_xp?: number | null
          viral_score?: number | null
          viral_tier?: string | null
        }
        Update: {
          badge_id?: string
          cast_hash?: string
          cast_url?: string
          created_at?: string
          fid?: number
          id?: string
          last_metrics_update?: string | null
          likes_count?: number | null
          recasts_count?: number | null
          replies_count?: number | null
          tier?: string
          viral_bonus_xp?: number | null
          viral_score?: number | null
          viral_tier?: string | null
        }
        Relationships: []
      }
      badge_templates: {
        Row: {
          active: boolean
          art_path: string | null
          badge_type: string
          chain: string
          created_at: string
          description: string | null
          id: string
          image_url: string | null
          metadata: Json | null
          name: string
          points_cost: number
          slug: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          art_path?: string | null
          badge_type: string
          chain: string
          created_at?: string
          description?: string | null
          id?: string
          image_url?: string | null
          metadata?: Json | null
          name: string
          points_cost?: number
          slug: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          art_path?: string | null
          badge_type?: string
          chain?: string
          created_at?: string
          description?: string | null
          id?: string
          image_url?: string | null
          metadata?: Json | null
          name?: string
          points_cost?: number
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      bot_metrics: {
        Row: {
          cast_hash: string | null
          created_at: string
          error_message: string | null
          fid: number | null
          id: number
          metadata: Json | null
          metric_type: string
          response_time_ms: number | null
        }
        Insert: {
          cast_hash?: string | null
          created_at?: string
          error_message?: string | null
          fid?: number | null
          id?: number
          metadata?: Json | null
          metric_type: string
          response_time_ms?: number | null
        }
        Update: {
          cast_hash?: string | null
          created_at?: string
          error_message?: string | null
          fid?: number | null
          id?: number
          metadata?: Json | null
          metric_type?: string
          response_time_ms?: number | null
        }
        Relationships: []
      }
      frame_sessions: {
        Row: {
          created_at: string
          fid: number
          session_id: string
          state: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          fid: number
          session_id: string
          state?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          fid?: number
          session_id?: string
          state?: Json
          updated_at?: string
        }
        Relationships: []
      }
      guild_events: {
        Row: {
          actor_address: string
          amount: number | null
          created_at: string | null
          event_type: string
          guild_id: string
          id: number
          metadata: Json | null
          target_address: string | null
        }
        Insert: {
          actor_address: string
          amount?: number | null
          created_at?: string | null
          event_type: string
          guild_id: string
          id?: number
          metadata?: Json | null
          target_address?: string | null
        }
        Update: {
          actor_address?: string
          amount?: number | null
          created_at?: string | null
          event_type?: string
          guild_id?: string
          id?: number
          metadata?: Json | null
          target_address?: string | null
        }
        Relationships: []
      }
      guild_off_chain_metadata: {
        Row: {
          banner: string | null
          description: string | null
          guild_id: string
          updated_at: string
        }
        Insert: {
          banner?: string | null
          description?: string | null
          guild_id: string
          updated_at?: string
        }
        Update: {
          banner?: string | null
          description?: string | null
          guild_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      leaderboard_snapshots: {
        Row: {
          address: string
          chain: string
          completed: number
          display_name: string | null
          farcaster_fid: number | null
          global: boolean
          id: number
          pfp_url: string | null
          points: number
          rank: number | null
          rewards: number
          season_alloc: number
          season_key: string
          updated_at: string
        }
        Insert: {
          address: string
          chain: string
          completed?: number
          display_name?: string | null
          farcaster_fid?: number | null
          global?: boolean
          id?: number
          pfp_url?: string | null
          points?: number
          rank?: number | null
          rewards?: number
          season_alloc?: number
          season_key?: string
          updated_at?: string
        }
        Update: {
          address?: string
          chain?: string
          completed?: number
          display_name?: string | null
          farcaster_fid?: number | null
          global?: boolean
          id?: number
          pfp_url?: string | null
          points?: number
          rank?: number | null
          rewards?: number
          season_alloc?: number
          season_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      maintenance_tasks: {
        Row: {
          category: string
          created_at: string | null
          dependencies: string[] | null
          description: string
          error_message: string | null
          estimated_time: number | null
          files: string[] | null
          fix_id: string | null
          fixed_at: string | null
          fixed_by: string | null
          id: string
          severity: string
          status: string
          title: string
          type: string
          updated_at: string | null
        }
        Insert: {
          category: string
          created_at?: string | null
          dependencies?: string[] | null
          description: string
          error_message?: string | null
          estimated_time?: number | null
          files?: string[] | null
          fix_id?: string | null
          fixed_at?: string | null
          fixed_by?: string | null
          id: string
          severity: string
          status?: string
          title: string
          type: string
          updated_at?: string | null
        }
        Update: {
          category?: string
          created_at?: string | null
          dependencies?: string[] | null
          description?: string
          error_message?: string | null
          estimated_time?: number | null
          files?: string[] | null
          fix_id?: string | null
          fixed_at?: string | null
          fixed_by?: string | null
          id?: string
          severity?: string
          status?: string
          title?: string
          type?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      miniapp_notification_tokens: {
        Row: {
          client_fid: number | null
          created_at: string
          fid: number
          id: string
          last_event: string | null
          last_event_at: string | null
          last_gm_context: Json | null
          last_gm_reference_at: string | null
          last_gm_reminder_sent_at: string | null
          last_seen_at: string
          notification_url: string
          status: string
          token: string
          updated_at: string
          wallet_address: string | null
        }
        Insert: {
          client_fid?: number | null
          created_at?: string
          fid: number
          id?: string
          last_event?: string | null
          last_event_at?: string | null
          last_gm_context?: Json | null
          last_gm_reference_at?: string | null
          last_gm_reminder_sent_at?: string | null
          last_seen_at?: string
          notification_url: string
          status?: string
          token: string
          updated_at?: string
          wallet_address?: string | null
        }
        Update: {
          client_fid?: number | null
          created_at?: string
          fid?: number
          id?: string
          last_event?: string | null
          last_event_at?: string | null
          last_gm_context?: Json | null
          last_gm_reference_at?: string | null
          last_gm_reminder_sent_at?: string | null
          last_seen_at?: string
          notification_url?: string
          status?: string
          token?: string
          updated_at?: string
          wallet_address?: string | null
        }
        Relationships: []
      }
      mint_queue: {
        Row: {
          badge_type: string
          created_at: string
          error: string | null
          fid: number
          id: number
          minted_at: string | null
          retry_count: number | null
          status: string
          tx_hash: string | null
          updated_at: string
          wallet_address: string
        }
        Insert: {
          badge_type?: string
          created_at?: string
          error?: string | null
          fid: number
          id?: number
          minted_at?: string | null
          retry_count?: number | null
          status?: string
          tx_hash?: string | null
          updated_at?: string
          wallet_address: string
        }
        Update: {
          badge_type?: string
          created_at?: string
          error?: string | null
          fid?: number
          id?: number
          minted_at?: string | null
          retry_count?: number | null
          status?: string
          tx_hash?: string | null
          updated_at?: string
          wallet_address?: string
        }
        Relationships: [
          {
            foreignKeyName: "mint_queue_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "points_leaderboard"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "mint_queue_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      nft_metadata: {
        Row: {
          animation_url: string | null
          attributes: Json | null
          category: string
          chain: string
          contract_address: string | null
          created_at: string
          current_supply: number | null
          description: string | null
          id: number
          image_url: string
          is_active: boolean | null
          max_supply: number | null
          mint_price_wei: string | null
          name: string
          nft_type_id: string
          rarity: string
          requirements: Json | null
          updated_at: string
        }
        Insert: {
          animation_url?: string | null
          attributes?: Json | null
          category: string
          chain: string
          contract_address?: string | null
          created_at?: string
          current_supply?: number | null
          description?: string | null
          id?: number
          image_url: string
          is_active?: boolean | null
          max_supply?: number | null
          mint_price_wei?: string | null
          name: string
          nft_type_id: string
          rarity: string
          requirements?: Json | null
          updated_at?: string
        }
        Update: {
          animation_url?: string | null
          attributes?: Json | null
          category?: string
          chain?: string
          contract_address?: string | null
          created_at?: string
          current_supply?: number | null
          description?: string | null
          id?: number
          image_url?: string
          is_active?: boolean | null
          max_supply?: number | null
          mint_price_wei?: string | null
          name?: string
          nft_type_id?: string
          rarity?: string
          requirements?: Json | null
          updated_at?: string
        }
        Relationships: []
      }
      notification_batch_queue: {
        Row: {
          created_at: string | null
          delivered_at: string | null
          failed_attempts: number | null
          fid: number
          id: number
          last_error: string | null
          notification_type: string
          payload: Json
          priority: number
          scheduled_for: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          delivered_at?: string | null
          failed_attempts?: number | null
          fid: number
          id?: number
          last_error?: string | null
          notification_type: string
          payload: Json
          priority?: number
          scheduled_for: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          delivered_at?: string | null
          failed_attempts?: number | null
          fid?: number
          id?: number
          last_error?: string | null
          notification_type?: string
          payload?: Json
          priority?: number
          scheduled_for?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      notification_preferences: {
        Row: {
          category_settings: Json | null
          created_at: string | null
          fid: number
          global_mute: boolean | null
          id: string
          min_priority_for_push: string | null
          mute_until: string | null
          priority_last_updated: string | null
          priority_settings: Json | null
          quiet_hours_enabled: boolean | null
          quiet_hours_end: string | null
          quiet_hours_start: string | null
          quiet_hours_timezone: string | null
          updated_at: string | null
          wallet_address: string | null
          xp_rewards_display: boolean | null
        }
        Insert: {
          category_settings?: Json | null
          created_at?: string | null
          fid: number
          global_mute?: boolean | null
          id?: string
          min_priority_for_push?: string | null
          mute_until?: string | null
          priority_last_updated?: string | null
          priority_settings?: Json | null
          quiet_hours_enabled?: boolean | null
          quiet_hours_end?: string | null
          quiet_hours_start?: string | null
          quiet_hours_timezone?: string | null
          updated_at?: string | null
          wallet_address?: string | null
          xp_rewards_display?: boolean | null
        }
        Update: {
          category_settings?: Json | null
          created_at?: string | null
          fid?: number
          global_mute?: boolean | null
          id?: string
          min_priority_for_push?: string | null
          mute_until?: string | null
          priority_last_updated?: string | null
          priority_settings?: Json | null
          quiet_hours_enabled?: boolean | null
          quiet_hours_end?: string | null
          quiet_hours_start?: string | null
          quiet_hours_timezone?: string | null
          updated_at?: string | null
          wallet_address?: string | null
          xp_rewards_display?: boolean | null
        }
        Relationships: []
      }
      partner_snapshots: {
        Row: {
          address: string
          balance: number
          chain: string
          computed_at: string
          eligible: boolean
          id: number
          metadata: Json | null
          partner: string
          reason: string | null
          requirement_address: string | null
          requirement_kind: string
          requirement_minimum: number
          requirement_token_id: number | null
          snapshot_id: string
        }
        Insert: {
          address: string
          balance?: number
          chain: string
          computed_at?: string
          eligible?: boolean
          id?: number
          metadata?: Json | null
          partner: string
          reason?: string | null
          requirement_address?: string | null
          requirement_kind: string
          requirement_minimum?: number
          requirement_token_id?: number | null
          snapshot_id: string
        }
        Update: {
          address?: string
          balance?: number
          chain?: string
          computed_at?: string
          eligible?: boolean
          id?: number
          metadata?: Json | null
          partner?: string
          reason?: string | null
          requirement_address?: string | null
          requirement_kind?: string
          requirement_minimum?: number
          requirement_token_id?: number | null
          snapshot_id?: string
        }
        Relationships: []
      }
      points_transactions: {
        Row: {
          amount: number
          points_balance_after: number
          created_at: string | null
          fid: number
          id: number
          metadata: Json | null
          source: string
        }
        Insert: {
          amount: number
          points_balance_after: number
          created_at?: string | null
          fid: number
          id?: number
          metadata?: Json | null
          source: string
        }
        Update: {
          amount?: number
          points_balance_after?: number
          created_at?: string | null
          fid?: number
          id?: number
          metadata?: Json | null
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "points_transactions_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "points_leaderboard"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "points_transactions_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      quest_completions: {
        Row: {
          completed_at: string
          completer_address: string
          completer_fid: number
          id: number
          nft_awarded_token_id: number | null
          points_awarded: number
          quest_id: number
          token_awarded: number | null
          verification_proof: Json
        }
        Insert: {
          completed_at?: string
          completer_address: string
          completer_fid: number
          id?: number
          nft_awarded_token_id?: number | null
          points_awarded?: number
          quest_id: number
          token_awarded?: number | null
          verification_proof?: Json
        }
        Update: {
          completed_at?: string
          completer_address?: string
          completer_fid?: number
          id?: number
          nft_awarded_token_id?: number | null
          points_awarded?: number
          quest_id?: number
          token_awarded?: number | null
          verification_proof?: Json
        }
        Relationships: [
          {
            foreignKeyName: "quest_completions_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "unified_quests"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_creation_costs: {
        Row: {
          breakdown: Json
          created_at: string | null
          creator_fid: number
          id: string
          is_refunded: boolean | null
          points_escrowed: number
          points_refunded: number | null
          quest_id: number | null  // Nullable - populated after quest creation
          refund_reason: string | null
          refunded_at: string | null
          total_cost: number
        }
        Insert: {
          breakdown: Json
          created_at?: string | null
          creator_fid: number
          id?: string
          is_refunded?: boolean | null
          points_escrowed: number
          points_refunded?: number | null
          quest_id?: number | null  // Nullable - populated after quest creation
          refund_reason?: string | null
          refunded_at?: string | null
          total_cost: number
        }
        Update: {
          breakdown?: Json
          created_at?: string | null
          creator_fid?: number
          id?: string
          is_refunded?: boolean | null
          points_escrowed?: number
          points_refunded?: number | null
          quest_id?: number | null  // Nullable - populated after quest creation
          refund_reason?: string | null
          refunded_at?: string | null
          total_cost?: number
        }
        Relationships: [
          {
            foreignKeyName: "quest_creation_costs_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "unified_quests"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_creator_earnings: {
        Row: {
          completions_count: number
          creator_fid: number
          id: number
          last_updated_at: string
          milestone_10_claimed: boolean
          milestone_100_claimed: boolean
          milestone_50_claimed: boolean
          points_earned: number
          quest_id: number
          viral_bonus_awarded: number
        }
        Insert: {
          completions_count?: number
          creator_fid: number
          id?: number
          last_updated_at?: string
          milestone_10_claimed?: boolean
          milestone_100_claimed?: boolean
          milestone_50_claimed?: boolean
          points_earned?: number
          quest_id: number
          viral_bonus_awarded?: number
        }
        Update: {
          completions_count?: number
          creator_fid?: number
          id?: number
          last_updated_at?: string
          milestone_10_claimed?: boolean
          milestone_100_claimed?: boolean
          milestone_50_claimed?: boolean
          points_earned?: number
          quest_id?: number
          viral_bonus_awarded?: number
        }
        Relationships: [
          {
            foreignKeyName: "quest_creator_earnings_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "unified_quests"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_definitions: {
        Row: {
          banner_path: string | null
          category: string
          completion_count: number
          created_at: string
          description: string
          difficulty: string
          end_date: string | null
          icon_path: string | null
          id: number
          is_active: boolean
          is_featured: boolean
          max_completions: number | null
          metadata: Json | null
          quest_name: string
          quest_slug: string
          quest_type: string
          requirements: Json
          reward_badges: string[] | null
          reward_points_awarded: number
          start_date: string | null
          updated_at: string
        }
        Insert: {
          banner_path?: string | null
          category: string
          completion_count?: number
          created_at?: string
          description: string
          difficulty?: string
          end_date?: string | null
          icon_path?: string | null
          id?: number
          is_active?: boolean
          is_featured?: boolean
          max_completions?: number | null
          metadata?: Json | null
          quest_name: string
          quest_slug: string
          quest_type: string
          requirements?: Json
          reward_badges?: string[] | null
          reward_points_awarded?: number
          reward_xp?: number
          start_date?: string | null
          updated_at?: string
        }
        Update: {
          banner_path?: string | null
          category?: string
          completion_count?: number
          created_at?: string
          description?: string
          difficulty?: string
          end_date?: string | null
          icon_path?: string | null
          id?: number
          is_active?: boolean
          is_featured?: boolean
          max_completions?: number | null
          metadata?: Json | null
          quest_name?: string
          quest_slug?: string
          quest_type?: string
          requirements?: Json
          reward_badges?: string[] | null
          reward_points_awarded?: number
          reward_xp?: number
          start_date?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      quest_templates: {
        Row: {
          banner_url: string | null
          category: string
          created_at: string
          default_reward_points: number
          default_reward_xp: number
          default_task_count: number
          description: string
          difficulty: string
          icon_url: string | null
          id: string
          is_active: boolean
          is_featured: boolean
          name: string
          slug: string
          suggested_badges: string[] | null
          task_presets: Json | null
          updated_at: string
          usage_count: number
        }
        Insert: {
          banner_url?: string | null
          category: string
          created_at?: string
          default_reward_points?: number
          default_reward_xp?: number
          default_task_count?: number
          description: string
          difficulty: string
          icon_url?: string | null
          id?: string
          is_active?: boolean
          is_featured?: boolean
          name: string
          slug: string
          suggested_badges?: string[] | null
          task_presets?: Json | null
          updated_at?: string
          usage_count?: number
        }
        Update: {
          banner_url?: string | null
          category?: string
          created_at?: string
          default_reward_points?: number
          default_reward_xp?: number
          default_task_count?: number
          description?: string
          difficulty?: string
          icon_url?: string | null
          id?: string
          is_active?: boolean
          is_featured?: boolean
          name?: string
          slug?: string
          suggested_badges?: string[] | null
          task_presets?: Json | null
          updated_at?: string
          usage_count?: number
        }
        Relationships: []
      }
      referral_activity: {
        Row: {
          event_type: string
          fid: number
          id: number
          metadata: Json | null
          points_awarded: number | null
          referral_code: string | null
          referred_fid: number | null
          timestamp: string
        }
        Insert: {
          event_type: string
          fid: number
          id?: number
          metadata?: Json | null
          points_awarded?: number | null
          referral_code?: string | null
          referred_fid?: number | null
          timestamp?: string
        }
        Update: {
          event_type?: string
          fid?: number
          id?: number
          metadata?: Json | null
          points_awarded?: number | null
          referral_code?: string | null
          referred_fid?: number | null
          timestamp?: string
        }
        Relationships: []
      }
      referral_period_comparison: {
        Row: {
          created_at: string | null
          fid: number
          id: number
          period: string
          points: number | null
          referrals: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          fid: number
          id?: number
          period: string
          points?: number | null
          referrals?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          fid?: number
          id?: number
          period?: string
          points?: number | null
          referrals?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      referral_registrations: {
        Row: {
          block_number: number | null
          created_at: string
          fid: number
          id: number
          referral_code: string
          referrer_code: string | null
          referrer_fid: number | null
          referrer_set_tx: string | null
          registered_at: string
          registration_tx: string | null
          updated_at: string
          wallet_address: string
        }
        Insert: {
          block_number?: number | null
          created_at?: string
          fid: number
          id?: number
          referral_code: string
          referrer_code?: string | null
          referrer_fid?: number | null
          referrer_set_tx?: string | null
          registered_at?: string
          registration_tx?: string | null
          updated_at?: string
          wallet_address: string
        }
        Update: {
          block_number?: number | null
          created_at?: string
          fid?: number
          id?: number
          referral_code?: string
          referrer_code?: string | null
          referrer_fid?: number | null
          referrer_set_tx?: string | null
          registered_at?: string
          registration_tx?: string | null
          updated_at?: string
          wallet_address?: string
        }
        Relationships: []
      }
      referral_stats: {
        Row: {
          address: string | null
          avatar: string | null
          conversion_rate: number | null
          created_at: string
          fid: number
          growth_rate: number | null
          id: number
          last_activity_at: string | null
          points_awarded: number
          rank: number | null
          rank_change: number | null
          successful_referrals: number
          tier: string | null
          total_referrals: number
          updated_at: string
          username: string | null
        }
        Insert: {
          address?: string | null
          avatar?: string | null
          conversion_rate?: number | null
          created_at?: string
          fid: number
          growth_rate?: number | null
          id?: number
          last_activity_at?: string | null
          points_awarded?: number
          rank?: number | null
          rank_change?: number | null
          successful_referrals?: number
          tier?: string | null
          total_referrals?: number
          updated_at?: string
          username?: string | null
        }
        Update: {
          address?: string | null
          avatar?: string | null
          conversion_rate?: number | null
          created_at?: string
          fid?: number
          growth_rate?: number | null
          id?: number
          last_activity_at?: string | null
          points_awarded?: number
          rank?: number | null
          rank_change?: number | null
          successful_referrals?: number
          tier?: string | null
          total_referrals?: number
          updated_at?: string
          username?: string | null
        }
        Relationships: []
      }
      referral_tier_distribution: {
        Row: {
          count: number | null
          created_at: string | null
          fid: number
          id: number
          tier: string
          updated_at: string | null
        }
        Insert: {
          count?: number | null
          created_at?: string | null
          fid: number
          id?: number
          tier: string
          updated_at?: string | null
        }
        Update: {
          count?: number | null
          created_at?: string | null
          fid?: number
          id?: number
          tier?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      referral_timeline: {
        Row: {
          created_at: string | null
          date: string
          fid: number
          id: number
          points: number | null
          referrals: number | null
        }
        Insert: {
          created_at?: string | null
          date: string
          fid: number
          id?: number
          points?: number | null
          referrals?: number | null
        }
        Update: {
          created_at?: string | null
          date?: string
          fid?: number
          id?: number
          points?: number | null
          referrals?: number | null
        }
        Relationships: []
      }
      reward_claims: {
        Row: {
          badge_prestige_claimed: number | null
          claimed_at: string | null
          created_at: string | null
          fid: number | null
          guild_points_claimed: number | null
          id: string
          oracle_address: string | null
          referral_bonus_claimed: number | null
          streak_bonus_claimed: number | null
          total_points_claimed: number
          tx_hash: string | null
          viral_points_claimed: number | null
          wallet_address: string
        }
        Insert: {
          badge_prestige_claimed?: number | null
          claimed_at?: string | null
          created_at?: string | null
          fid?: number | null
          guild_points_claimed?: number | null
          id?: string
          oracle_address?: string | null
          referral_bonus_claimed?: number | null
          streak_bonus_claimed?: number | null
          total_points_claimed: number
          tx_hash?: string | null
          viral_points_claimed?: number | null
          wallet_address: string
        }
        Update: {
          badge_prestige_claimed?: number | null
          claimed_at?: string | null
          created_at?: string | null
          fid?: number | null
          guild_points_claimed?: number | null
          id?: string
          oracle_address?: string | null
          referral_bonus_claimed?: number | null
          streak_bonus_claimed?: number | null
          total_points_claimed?: number
          tx_hash?: string | null
          viral_points_claimed?: number | null
          wallet_address?: string
        }
        Relationships: []
      }
      task_completions: {
        Row: {
          id: number
          quest_id: number
          task_index: number
          user_fid: number
          verification_proof: Json
          verified_at: string
        }
        Insert: {
          id?: number
          quest_id: number
          task_index: number
          user_fid: number
          verification_proof?: Json
          verified_at?: string
        }
        Update: {
          id?: number
          quest_id?: number
          task_index?: number
          user_fid?: number
          verification_proof?: Json
          verified_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_completions_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "unified_quests"
            referencedColumns: ["id"]
          },
        ]
      }
      testimonials: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          display_order: number | null
          fid: number | null
          id: string
          is_featured: boolean | null
          quote: string
          role: string
          updated_at: string | null
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          display_order?: number | null
          fid?: number | null
          id?: string
          is_featured?: boolean | null
          quote: string
          role: string
          updated_at?: string | null
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          display_order?: number | null
          fid?: number | null
          id?: string
          is_featured?: boolean | null
          quote?: string
          role?: string
          updated_at?: string | null
          username?: string
        }
        Relationships: []
      }
      unified_quests: {
        Row: {
          badge_image_url: string | null
          category: string
          completion_count: number
          cover_image_url: string | null
          created_at: string
          creation_cost: number
          creator_address: string
          creator_earnings_percent: number
          creator_fid: number
          description: string
          difficulty: string | null
          escrow_tx_hash: string | null
          estimated_time_minutes: number | null
          expiry_date: string | null
          featured_order: number | null
          id: number
          is_featured: boolean | null
          last_synced_at: string | null
          max_completions: number | null
          min_viral_xp_required: number | null
          onchain_quest_id: number | null
          onchain_status: string | null
          participant_count: number | null
          quest_image_storage_path: string | null
          quest_image_url: string | null
          refunded_at: string | null
          reward_mode: string
          reward_nft_address: string | null
          reward_nft_token_id: number | null
          reward_points_awarded: number
          reward_token_address: string | null
          reward_token_amount: number | null
          slug: string
          status: string
          tags: string[] | null
          tasks: Json | null
          thumbnail_url: string | null
          title: string
          total_completions: number
          total_points_awarded: number
          type: string
          updated_at: string
          verification_data: Json
        }
        Insert: {
          badge_image_url?: string | null
          category: string
          completion_count?: number
          cover_image_url?: string | null
          created_at?: string
          creation_cost?: number
          creator_address: string
          creator_earnings_percent?: number
          creator_fid: number
          description: string
          difficulty?: string | null
          escrow_tx_hash?: string | null
          estimated_time_minutes?: number | null
          expiry_date?: string | null
          featured_order?: number | null
          id?: number
          is_featured?: boolean | null
          last_synced_at?: string | null
          max_completions?: number | null
          min_viral_xp_required?: number | null
          onchain_quest_id?: number | null
          onchain_status?: string | null
          participant_count?: number | null
          quest_image_storage_path?: string | null
          quest_image_url?: string | null
          reward_mode?: string
          reward_nft_address?: string | null
          reward_nft_token_id?: number | null
          reward_points_awarded?: number
          reward_token_address?: string | null
          reward_token_amount?: number | null
          slug: string
          status?: string
          tags?: string[] | null
          tasks?: Json | null
          thumbnail_url?: string | null
          title: string
          total_completions?: number
          total_points_awarded?: number
          type: string
          updated_at?: string
          verification_data?: Json
        }
        Update: {
          badge_image_url?: string | null
          category?: string
          completion_count?: number
          cover_image_url?: string | null
          created_at?: string
          creation_cost?: number
          creator_address?: string
          creator_earnings_percent?: number
          creator_fid?: number
          description?: string
          difficulty?: string | null
          escrow_tx_hash?: string | null
          estimated_time_minutes?: number | null
          expiry_date?: string | null
          featured_order?: number | null
          id?: number
          is_featured?: boolean | null
          last_synced_at?: string | null
          max_completions?: number | null
          min_viral_xp_required?: number | null
          onchain_quest_id?: number | null
          onchain_status?: string | null
          participant_count?: number | null
          quest_image_storage_path?: string | null
          quest_image_url?: string | null
          reward_mode?: string
          reward_nft_address?: string | null
          reward_nft_token_id?: number | null
          reward_points_awarded?: number
          reward_token_address?: string | null
          reward_token_amount?: number | null
          slug?: string
          status?: string
          tags?: string[] | null
          tasks?: Json | null
          thumbnail_url?: string | null
          title?: string
          total_completions?: number
          total_earned_points?: number
          type?: string
          updated_at?: string
          verification_data?: Json
        }
        Relationships: []
      }
      user_badges: {
        Row: {
          animation_url: string | null
          assigned_at: string
          badge_id: string
          badge_type: string
          category: string | null
          chain: string | null
          contract_address: string | null
          created_at: string
          current_supply: number | null
          fid: number
          id: number
          image_url: string | null
          max_supply: number | null
          metadata: Json | null
          minted: boolean | null
          minted_at: string | null
          nft_type: string | null
          nft_type_id: string | null
          rarity: string | null
          tier: string
          token_id: number | null
          tx_hash: string | null
          updated_at: string
        }
        Insert: {
          animation_url?: string | null
          assigned_at?: string
          badge_id: string
          badge_type: string
          category?: string | null
          chain?: string | null
          contract_address?: string | null
          created_at?: string
          current_supply?: number | null
          fid: number
          id?: number
          image_url?: string | null
          max_supply?: number | null
          metadata?: Json | null
          minted?: boolean | null
          minted_at?: string | null
          nft_type?: string | null
          nft_type_id?: string | null
          rarity?: string | null
          tier?: string
          token_id?: number | null
          tx_hash?: string | null
          updated_at?: string
        }
        Update: {
          animation_url?: string | null
          assigned_at?: string
          badge_id?: string
          badge_type?: string
          category?: string | null
          chain?: string | null
          contract_address?: string | null
          created_at?: string
          current_supply?: number | null
          fid?: number
          id?: number
          image_url?: string | null
          max_supply?: number | null
          metadata?: Json | null
          minted?: boolean | null
          minted_at?: string | null
          nft_type?: string | null
          nft_type_id?: string | null
          rarity?: string | null
          tier?: string
          token_id?: number | null
          tx_hash?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_badges_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "points_leaderboard"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "user_badges_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      user_notification_history: {
        Row: {
          action_href: string | null
          action_label: string | null
          category: string
          created_at: string
          description: string | null
          dismissed_at: string | null
          fid: number | null
          id: string
          metadata: Json | null
          read_at: string | null
          title: string
          tone: string
          wallet_address: string | null
        }
        Insert: {
          action_href?: string | null
          action_label?: string | null
          category: string
          created_at?: string
          description?: string | null
          dismissed_at?: string | null
          fid?: number | null
          id?: string
          metadata?: Json | null
          read_at?: string | null
          title: string
          tone: string
          wallet_address?: string | null
        }
        Update: {
          action_href?: string | null
          action_label?: string | null
          category?: string
          created_at?: string
          description?: string | null
          dismissed_at?: string | null
          fid?: number | null
          id?: string
          metadata?: Json | null
          read_at?: string | null
          title?: string
          tone?: string
          wallet_address?: string | null
        }
        Relationships: []
      }
      user_points_balances: {
        Row: {
          points_balance: number
          fid: number
          guild_points_awarded: number
          last_synced_at: string
          total_score: number
          updated_at: string
          viral_xp: number
        }
        Insert: {
          points_balance?: number
          fid: number
          guild_points_awarded?: number
          last_synced_at?: string
          total_score?: number
          updated_at?: string
          viral_xp?: number
        }
        Update: {
          points_balance?: number
          fid?: number
          guild_points_awarded?: number
          last_synced_at?: string
          total_score?: number
          updated_at?: string
          viral_xp?: number
        }
        Relationships: []
      }
      user_profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          cover_image_url: string | null
          created_at: string | null
          custody_address: string | null
          display_name: string | null
          fid: number
          id: string
          metadata: Json | null
          neynar_score: number | null
          neynar_tier: string | null
          og_nft_eligible: boolean | null
          onboarded_at: string | null
          points_balance: number | null
          social_links: Json | null
          total_earned_from_gms: number | null
          total_points_spent: number | null
          updated_at: string | null
          verified_addresses: string[] | null
          wallet_address: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          cover_image_url?: string | null
          created_at?: string | null
          custody_address?: string | null
          display_name?: string | null
          fid: number
          id?: string
          metadata?: Json | null
          neynar_score?: number | null
          neynar_tier?: string | null
          og_nft_eligible?: boolean | null
          onboarded_at?: string | null
          points_balance?: number | null
          social_links?: Json | null
          total_earned_from_gms?: number | null
          total_points_spent?: number | null
          updated_at?: string | null
          verified_addresses?: string[] | null
          wallet_address?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          cover_image_url?: string | null
          created_at?: string | null
          custody_address?: string | null
          display_name?: string | null
          fid?: number
          id?: string
          metadata?: Json | null
          neynar_score?: number | null
          neynar_tier?: string | null
          og_nft_eligible?: boolean | null
          onboarded_at?: string | null
          points_balance?: number | null
          social_links?: Json | null
          total_earned_from_gms?: number | null
          total_points_spent?: number | null
          updated_at?: string | null
          verified_addresses?: string[] | null
          wallet_address?: string | null
        }
        Relationships: []
      }
      user_quest_progress: {
        Row: {
          completed_at: string | null
          completed_tasks: number[] | null
          current_task_index: number
          id: number
          last_activity_at: string
          progress_percentage: number
          quest_id: number
          started_at: string
          status: string
          user_fid: number
        }
        Insert: {
          completed_at?: string | null
          completed_tasks?: number[] | null
          current_task_index?: number
          id?: number
          last_activity_at?: string
          progress_percentage?: number
          quest_id: number
          started_at?: string
          status?: string
          user_fid: number
        }
        Update: {
          completed_at?: string | null
          completed_tasks?: number[] | null
          current_task_index?: number
          id?: number
          last_activity_at?: string
          progress_percentage?: number
          quest_id?: number
          started_at?: string
          status?: string
          user_fid?: number
        }
        Relationships: [
          {
            foreignKeyName: "user_quest_progress_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "unified_quests"
            referencedColumns: ["id"]
          },
        ]
      }
      user_quests: {
        Row: {
          claimed_at: string | null
          completed_at: string | null
          created_at: string
          expires_at: string | null
          fid: number
          id: number
          metadata: Json | null
          progress: Json
          quest_id: number
          started_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          claimed_at?: string | null
          completed_at?: string | null
          created_at?: string
          expires_at?: string | null
          fid: number
          id?: number
          metadata?: Json | null
          progress?: Json
          quest_id: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          claimed_at?: string | null
          completed_at?: string | null
          created_at?: string
          expires_at?: string | null
          fid?: number
          id?: number
          metadata?: Json | null
          progress?: Json
          quest_id?: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_quests_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "points_leaderboard"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "user_quests_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "user_quests_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quest_definitions"
            referencedColumns: ["id"]
          },
        ]
      }
      viral_share_events: {
        Row: {
          bonus_awarded: boolean | null
          bonus_points: number | null
          cast_hash: string | null
          cast_url: string | null
          created_at: string | null
          fid: number
          id: string
          share_platform: string | null
          tier: string
        }
        Insert: {
          bonus_awarded?: boolean | null
          bonus_points?: number | null
          cast_hash?: string | null
          cast_url?: string | null
          created_at?: string | null
          fid: number
          id?: string
          share_platform?: string | null
          tier: string
        }
        Update: {
          bonus_awarded?: boolean | null
          bonus_points?: number | null
          cast_hash?: string | null
          cast_url?: string | null
          created_at?: string | null
          fid?: number
          id?: string
          share_platform?: string | null
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "fk_user_profile"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "points_leaderboard"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "fk_user_profile"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
    }
    Views: {
      gmeow_badge_adventure: {
        Row: {
          active: boolean | null
          art_path: string | null
          badge_type: string | null
          chain: string | null
          created_at: string | null
          description: string | null
          id: string | null
          image_url: string | null
          metadata: Json | null
          name: string | null
          points_cost: number | null
          slug: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          art_path?: string | null
          badge_type?: string | null
          chain?: string | null
          created_at?: string | null
          description?: string | null
          id?: string | null
          image_url?: string | null
          metadata?: Json | null
          name?: string | null
          points_cost?: number | null
          slug?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          art_path?: string | null
          badge_type?: string | null
          chain?: string | null
          created_at?: string | null
          description?: string | null
          id?: string | null
          image_url?: string | null
          metadata?: Json | null
          name?: string | null
          points_cost?: number | null
          slug?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      points_leaderboard: {
        Row: {
          current_points: number | null
          fid: number | null
          points_rank: number | null
          total_points_earned: number | null
          total_points_spent: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      get_guild_stats_atomic: {
        Args: {
          p_guild_id: string
        }
        Returns: {
          guild_id: string
          leader_address: string
          total_points: number
          member_count: number
          level: number
          officers: Json
          member_points: Json
          member_addresses: string[]
        }[]
      }
      [key: string]: any
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
