/**
 * Supabase Database Types - Auto-generated by MCP
 * Generated: 2025-11-28
 * 
 * DO NOT EDIT MANUALLY
 * Regenerate with: mcp_my-mcp-server_generate_typescript_types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      badge_casts: {
        Row: {
          badge_id: string
          cast_hash: string
          cast_url: string
          created_at: string
          fid: number
          id: string
          last_metrics_update: string | null
          likes_count: number | null
          recasts_count: number | null
          replies_count: number | null
          tier: string
          viral_bonus_xp: number | null
          viral_score: number | null
          viral_tier: string | null
        }
        Insert: {
          badge_id: string
          cast_hash: string
          cast_url: string
          created_at?: string
          fid: number
          id?: string
          last_metrics_update?: string | null
          likes_count?: number | null
          recasts_count?: number | null
          replies_count?: number | null
          tier: string
          viral_bonus_xp?: number | null
          viral_score?: number | null
          viral_tier?: string | null
        }
        Update: {
          badge_id?: string
          cast_hash?: string
          cast_url?: string
          created_at?: string
          fid?: number
          id?: string
          last_metrics_update?: string | null
          likes_count?: number | null
          recasts_count?: number | null
          replies_count?: number | null
          tier?: string
          viral_bonus_xp?: number | null
          viral_score?: number | null
          viral_tier?: string | null
        }
        Relationships: []
      }
      badge_templates: {
        Row: {
          active: boolean
          art_path: string | null
          badge_type: string
          chain: string
          created_at: string
          description: string | null
          id: string
          image_url: string | null
          metadata: Json | null
          name: string
          points_cost: number
          slug: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          art_path?: string | null
          badge_type: string
          chain: string
          created_at?: string
          description?: string | null
          id?: string
          image_url?: string | null
          metadata?: Json | null
          name: string
          points_cost?: number
          slug: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          art_path?: string | null
          badge_type?: string
          chain?: string
          created_at?: string
          description?: string | null
          id?: string
          image_url?: string | null
          metadata?: Json | null
          name?: string
          points_cost?: number
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      frame_sessions: {
        Row: {
          created_at: string
          fid: number
          session_id: string
          state: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          fid: number
          session_id: string
          state?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          fid?: number
          session_id?: string
          state?: Json
          updated_at?: string
        }
        Relationships: []
      }
      gmeow_rank_events: {
        Row: {
          chain: string
          created_at: string
          delta: number
          event_type: string
          fid: number | null
          id: string
          level: number
          metadata: Json | null
          previous_points: number | null
          quest_id: number | null
          tier_name: string
          tier_percent: number
          total_points: number
          wallet_address: string
        }
        Insert: {
          chain: string
          created_at?: string
          delta: number
          event_type: string
          fid?: number | null
          id?: string
          level: number
          metadata?: Json | null
          previous_points?: number | null
          quest_id?: number | null
          tier_name: string
          tier_percent: number
          total_points: number
          wallet_address: string
        }
        Update: {
          chain?: string
          created_at?: string
          delta?: number
          event_type?: string
          fid?: number | null
          id?: string
          level?: number
          metadata?: Json | null
          previous_points?: number | null
          quest_id?: number | null
          tier_name?: string
          tier_percent?: number
          total_points?: number
          wallet_address?: string
        }
        Relationships: []
      }
      leaderboard_snapshots: {
        Row: {
          address: string
          chain: string
          completed: number
          display_name: string | null
          farcaster_fid: number | null
          global: boolean
          id: number
          pfp_url: string | null
          points: number
          rank: number | null
          rewards: number
          season_alloc: number
          season_key: string
          updated_at: string
        }
        Insert: {
          address: string
          chain: string
          completed?: number
          display_name?: string | null
          farcaster_fid?: number | null
          global?: boolean
          id?: number
          pfp_url?: string | null
          points?: number
          rank?: number | null
          rewards?: number
          season_alloc?: number
          season_key?: string
          updated_at?: string
        }
        Update: {
          address?: string
          chain?: string
          completed?: number
          display_name?: string | null
          farcaster_fid?: number | null
          global?: boolean
          id?: number
          pfp_url?: string | null
          points?: number
          rank?: number | null
          rewards?: number
          season_alloc?: number
          season_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      maintenance_tasks: {
        Row: {
          category: string
          created_at: string | null
          dependencies: string[] | null
          description: string
          error_message: string | null
          estimated_time: number | null
          files: string[] | null
          fix_id: string | null
          fixed_at: string | null
          fixed_by: string | null
          id: string
          severity: string
          status: string
          title: string
          type: string
          updated_at: string | null
        }
        Insert: {
          category: string
          created_at?: string | null
          dependencies?: string[] | null
          description: string
          error_message?: string | null
          estimated_time?: number | null
          files?: string[] | null
          fix_id?: string | null
          fixed_at?: string | null
          fixed_by?: string | null
          id: string
          severity: string
          status?: string
          title: string
          type: string
          updated_at?: string | null
        }
        Update: {
          category?: string
          created_at?: string | null
          dependencies?: string[] | null
          description?: string
          error_message?: string | null
          estimated_time?: number | null
          files?: string[] | null
          fix_id?: string | null
          fixed_at?: string | null
          fixed_by?: string | null
          id?: string
          severity?: string
          status?: string
          title?: string
          type?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      miniapp_notification_tokens: {
        Row: {
          client_fid: number | null
          created_at: string
          fid: number
          id: string
          last_event: string | null
          last_event_at: string | null
          last_gm_context: Json | null
          last_gm_reference_at: string | null
          last_gm_reminder_sent_at: string | null
          last_seen_at: string
          notification_url: string
          status: string
          token: string
          updated_at: string
          wallet_address: string | null
        }
        Insert: {
          client_fid?: number | null
          created_at?: string
          fid: number
          id?: string
          last_event?: string | null
          last_event_at?: string | null
          last_gm_context?: Json | null
          last_gm_reference_at?: string | null
          last_gm_reminder_sent_at?: string | null
          last_seen_at?: string
          notification_url: string
          status?: string
          token: string
          updated_at?: string
          wallet_address?: string | null
        }
        Update: {
          client_fid?: number | null
          created_at?: string
          fid?: number
          id?: string
          last_event?: string | null
          last_event_at?: string | null
          last_gm_context?: Json | null
          last_gm_reference_at?: string | null
          last_gm_reminder_sent_at?: string | null
          last_seen_at?: string
          notification_url?: string
          status?: string
          token?: string
          updated_at?: string
          wallet_address?: string | null
        }
        Relationships: []
      }
      mint_queue: {
        Row: {
          badge_type: string
          created_at: string
          error: string | null
          fid: number
          id: number
          minted_at: string | null
          retry_count: number | null
          status: string
          tx_hash: string | null
          updated_at: string
          wallet_address: string
        }
        Insert: {
          badge_type?: string
          created_at?: string
          error?: string | null
          fid: number
          id?: number
          minted_at?: string | null
          retry_count?: number | null
          status?: string
          tx_hash?: string | null
          updated_at?: string
          wallet_address: string
        }
        Update: {
          badge_type?: string
          created_at?: string
          error?: string | null
          fid?: number
          id?: number
          minted_at?: string | null
          retry_count?: number | null
          status?: string
          tx_hash?: string | null
          updated_at?: string
          wallet_address?: string
        }
        Relationships: [
          {
            foreignKeyName: "mint_queue_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      partner_snapshots: {
        Row: {
          address: string
          balance: number
          chain: string
          computed_at: string
          eligible: boolean
          id: number
          metadata: Json | null
          partner: string
          reason: string | null
          requirement_address: string | null
          requirement_kind: string
          requirement_minimum: number
          requirement_token_id: number | null
          snapshot_id: string
        }
        Insert: {
          address: string
          balance?: number
          chain: string
          computed_at?: string
          eligible?: boolean
          id?: number
          metadata?: Json | null
          partner: string
          reason?: string | null
          requirement_address?: string | null
          requirement_kind: string
          requirement_minimum?: number
          requirement_token_id?: number | null
          snapshot_id: string
        }
        Update: {
          address?: string
          balance?: number
          chain?: string
          computed_at?: string
          eligible?: boolean
          id?: number
          metadata?: Json | null
          partner?: string
          reason?: string | null
          requirement_address?: string | null
          requirement_kind?: string
          requirement_minimum?: number
          requirement_token_id?: number | null
          snapshot_id?: string
        }
        Relationships: []
      }
      quest_definitions: {
        Row: {
          banner_path: string | null
          category: string
          completion_count: number
          created_at: string
          description: string
          difficulty: string
          end_date: string | null
          icon_path: string | null
          id: number
          is_active: boolean
          is_featured: boolean
          max_completions: number | null
          metadata: Json | null
          quest_name: string
          quest_slug: string
          quest_type: string
          requirements: Json
          reward_badges: string[] | null
          reward_points: number
          reward_xp: number
          start_date: string | null
          updated_at: string
        }
        Insert: {
          banner_path?: string | null
          category: string
          completion_count?: number
          created_at?: string
          description: string
          difficulty?: string
          end_date?: string | null
          icon_path?: string | null
          id?: number
          is_active?: boolean
          is_featured?: boolean
          max_completions?: number | null
          metadata?: Json | null
          quest_name: string
          quest_slug: string
          quest_type: string
          requirements?: Json
          reward_badges?: string[] | null
          reward_points?: number
          reward_xp?: number
          start_date?: string | null
          updated_at?: string
        }
        Update: {
          banner_path?: string | null
          category?: string
          completion_count?: number
          created_at?: string
          description?: string
          difficulty?: string
          end_date?: string | null
          icon_path?: string | null
          id?: number
          is_active?: boolean
          is_featured?: boolean
          max_completions?: number | null
          metadata?: Json | null
          quest_name?: string
          quest_slug?: string
          quest_type?: string
          requirements?: Json
          reward_badges?: string[] | null
          reward_points?: number
          reward_xp?: number
          start_date?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      testimonials: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          display_order: number | null
          fid: number | null
          id: string
          is_featured: boolean | null
          quote: string
          role: string
          updated_at: string | null
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          display_order?: number | null
          fid?: number | null
          id?: string
          is_featured?: boolean | null
          quote: string
          role: string
          updated_at?: string | null
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          display_order?: number | null
          fid?: number | null
          id?: string
          is_featured?: boolean | null
          quote?: string
          role?: string
          updated_at?: string | null
          username?: string
        }
        Relationships: []
      }
      user_badges: {
        Row: {
          assigned_at: string
          badge_id: string
          badge_type: string
          chain: string | null
          contract_address: string | null
          created_at: string
          fid: number
          id: number
          metadata: Json | null
          minted: boolean | null
          minted_at: string | null
          tier: string
          token_id: number | null
          tx_hash: string | null
          updated_at: string
        }
        Insert: {
          assigned_at?: string
          badge_id: string
          badge_type: string
          chain?: string | null
          contract_address?: string | null
          created_at?: string
          fid: number
          id?: number
          metadata?: Json | null
          minted?: boolean | null
          minted_at?: string | null
          tier?: string
          token_id?: number | null
          tx_hash?: string | null
          updated_at?: string
        }
        Update: {
          assigned_at?: string
          badge_id?: string
          badge_type?: string
          chain?: string | null
          contract_address?: string | null
          created_at?: string
          fid?: number
          id?: number
          metadata?: Json | null
          minted?: boolean | null
          minted_at?: string | null
          tier?: string
          token_id?: number | null
          tx_hash?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_badges_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      user_notification_history: {
        Row: {
          action_href: string | null
          action_label: string | null
          category: string
          created_at: string
          description: string | null
          dismissed_at: string | null
          fid: number | null
          id: string
          metadata: Json | null
          title: string
          tone: string
          wallet_address: string | null
        }
        Insert: {
          action_href?: string | null
          action_label?: string | null
          category: string
          created_at?: string
          description?: string | null
          dismissed_at?: string | null
          fid?: number | null
          id?: string
          metadata?: Json | null
          title: string
          tone: string
          wallet_address?: string | null
        }
        Update: {
          action_href?: string | null
          action_label?: string | null
          category?: string
          created_at?: string
          description?: string | null
          dismissed_at?: string | null
          fid?: number | null
          id?: string
          metadata?: Json | null
          title?: string
          tone?: string
          wallet_address?: string | null
        }
        Relationships: []
      }
      user_profiles: {
        Row: {
          created_at: string | null
          custody_address: string | null
          fid: number
          id: string
          metadata: Json | null
          neynar_score: number | null
          neynar_tier: string | null
          og_nft_eligible: boolean | null
          onboarded_at: string | null
          points: number | null
          updated_at: string | null
          verified_addresses: string[] | null
          wallet_address: string | null
          xp: number | null
        }
        Insert: {
          created_at?: string | null
          custody_address?: string | null
          fid: number
          id?: string
          metadata?: Json | null
          neynar_score?: number | null
          neynar_tier?: string | null
          og_nft_eligible?: boolean | null
          onboarded_at?: string | null
          points?: number | null
          updated_at?: string | null
          verified_addresses?: string[] | null
          wallet_address?: string | null
          xp?: number | null
        }
        Update: {
          created_at?: string | null
          custody_address?: string | null
          fid?: number
          id?: string
          metadata?: Json | null
          neynar_score?: number | null
          neynar_tier?: string | null
          og_nft_eligible?: boolean | null
          onboarded_at?: string | null
          points?: number | null
          updated_at?: string | null
          verified_addresses?: string[] | null
          wallet_address?: string | null
          xp?: number | null
        }
        Relationships: []
      }
      user_quests: {
        Row: {
          claimed_at: string | null
          completed_at: string | null
          created_at: string
          expires_at: string | null
          fid: number
          id: number
          metadata: Json | null
          progress: Json
          quest_id: number
          started_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          claimed_at?: string | null
          completed_at?: string | null
          created_at?: string
          expires_at?: string | null
          fid: number
          id?: number
          metadata?: Json | null
          progress?: Json
          quest_id: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          claimed_at?: string | null
          completed_at?: string | null
          created_at?: string
          expires_at?: string | null
          fid?: number
          id?: number
          metadata?: Json | null
          progress?: Json
          quest_id?: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_quests_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
          {
            foreignKeyName: "user_quests_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quest_definitions"
            referencedColumns: ["id"]
          },
        ]
      }
      viral_milestone_achievements: {
        Row: {
          achieved_at: string | null
          achievement_type: string
          cast_hash: string | null
          fid: number
          id: string
          metadata: Json | null
          notification_sent: boolean | null
          notification_sent_at: string | null
        }
        Insert: {
          achieved_at?: string | null
          achievement_type: string
          cast_hash?: string | null
          fid: number
          id?: string
          metadata?: Json | null
          notification_sent?: boolean | null
          notification_sent_at?: string | null
        }
        Update: {
          achieved_at?: string | null
          achievement_type?: string
          cast_hash?: string | null
          fid?: number
          id?: string
          metadata?: Json | null
          notification_sent?: boolean | null
          notification_sent_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "viral_milestone_achievements_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      viral_share_events: {
        Row: {
          bonus_awarded: boolean | null
          bonus_points: number | null
          cast_hash: string | null
          cast_url: string | null
          created_at: string | null
          fid: number
          id: string
          share_platform: string | null
          tier: string
        }
        Insert: {
          bonus_awarded?: boolean | null
          bonus_points?: number | null
          cast_hash?: string | null
          cast_url?: string | null
          created_at?: string | null
          fid: number
          id?: string
          share_platform?: string | null
          tier: string
        }
        Update: {
          bonus_awarded?: boolean | null
          bonus_points?: number | null
          cast_hash?: string | null
          cast_url?: string | null
          created_at?: string | null
          fid?: number
          id?: string
          share_platform?: string | null
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "fk_user_profile"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      viral_tier_history: {
        Row: {
          cast_hash: string
          changed_at: string | null
          fid: number
          id: string
          new_score: number
          new_tier: string
          notification_sent: boolean | null
          notification_sent_at: string | null
          old_score: number
          old_tier: string
          xp_bonus_awarded: number
        }
        Insert: {
          cast_hash: string
          changed_at?: string | null
          fid: number
          id?: string
          new_score: number
          new_tier: string
          notification_sent?: boolean | null
          notification_sent_at?: string | null
          old_score: number
          old_tier: string
          xp_bonus_awarded: number
        }
        Update: {
          cast_hash?: string
          changed_at?: string | null
          fid?: number
          id?: string
          new_score?: number
          new_tier?: string
          notification_sent?: boolean | null
          notification_sent_at?: string | null
          old_score?: number
          old_tier?: string
          xp_bonus_awarded?: number
        }
        Relationships: [
          {
            foreignKeyName: "viral_tier_history_fid_fkey"
            columns: ["fid"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["fid"]
          },
        ]
      }
      xp_transactions: {
        Row: {
          amount: number
          created_at: string | null
          fid: number
          id: string
          source: string
        }
        Insert: {
          amount: number
          created_at?: string | null
          fid: number
          id?: string
          source: string
        }
        Update: {
          amount?: number
          created_at?: string | null
          fid?: number
          id?: string
          source?: string
        }
        Relationships: []
      }
    }
    Views: {
      gmeow_badge_adventure: {
        Row: {
          active: boolean | null
          art_path: string | null
          badge_type: string | null
          chain: string | null
          created_at: string | null
          description: string | null
          id: string | null
          image_url: string | null
          metadata: Json | null
          name: string | null
          points_cost: number | null
          slug: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          art_path?: string | null
          badge_type?: string | null
          chain?: string | null
          created_at?: string | null
          description?: string | null
          id?: string | null
          image_url?: string | null
          metadata?: Json | null
          name?: string | null
          points_cost?: number | null
          slug?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          art_path?: string | null
          badge_type?: string | null
          chain?: string | null
          created_at?: string | null
          description?: string | null
          id?: string | null
          image_url?: string | null
          metadata?: Json | null
          name?: string | null
          points_cost?: number | null
          slug?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      pending_viral_notifications: {
        Row: {
          achievement_type: string | null
          cast_hash: string | null
          fid: number | null
          id: string | null
          notification_type: string | null
          tier: string | null
          triggered_at: string | null
          xp_bonus: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      cleanup_expired_frame_sessions: { Args: never; Returns: number }
      cleanup_old_notifications: { Args: never; Returns: undefined }
      get_platform_stats: { Args: never; Returns: Json }
      http_get_config: { Args: { name: string }; Returns: string }
      http_refresh_schema_cache: { Args: never; Returns: undefined }
      http_set_config: {
        Args: { name: string; value: string }
        Returns: undefined
      }
      increment_user_xp: {
        Args: { p_fid: number; p_source?: string; p_xp_amount: number }
        Returns: undefined
      }
      mark_notification_sent: {
        Args: { p_id: string; p_notification_type: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
