// Generated by Supabase MCP on December 22, 2025
// Re-export types from supabase.generated.ts (DO NOT duplicate type definitions)
//
// ═══════════════════════════════════════════════════════════════════════════
// 🎯 MIGRATION WORKFLOW (Read Before Making Changes)
// ═══════════════════════════════════════════════════════════════════════════
//
// PRODUCTION STATUS (Dec 25, 2025):
// ✅ LIVE: Supabase database + Next.js API routes
// ⏸️ TESTING: Subsquid indexer (localhost only - not in production)
// 🎯 PLAN: Deploy Subsquid after all migrations + page audits complete
//
// HOW TO APPLY DATABASE MIGRATIONS:
// 1. Create SQL file: supabase/migrations/YYYYMMDDHHMMSS_description.sql
// 2. Apply via MCP: mcp_supabase_apply_migration(name: string, query: string)
// 3. Verify: mcp_supabase_list_tables(['public'])
// 4. Update types in supabase.generated.ts MANUALLY (see that file's header)
//
// ❌ NEVER run: npx supabase gen types typescript
// ❌ NEVER regenerate types from scratch
// ✅ ALWAYS use Supabase MCP for migrations
// ✅ ALWAYS manually update supabase.generated.ts
//
// ═══════════════════════════════════════════════════════════════════════════
// 🎯 POINTS NAMING CONVENTION (Contract = Source of Truth)
// ═══════════════════════════════════════════════════════════════════════════
//
// See: POINTS-NAMING-CONVENTION.md, MULTI-WALLET-CACHE-ARCHITECTURE.md
//
// 4-Layer Architecture:
// - Contract (Layer 1): pointsBalance, treasuryPoints (camelCase - SOURCE OF TRUTH)
// - Subsquid (Layer 2): pointsBalance, treasuryPoints (camelCase - exact match)
// - Supabase (Layer 3): points_balance, treasury_points (snake_case)
// - API (Layer 4): pointsBalance, treasuryPoints (camelCase)
//
// MIGRATION UPDATE (2025-12-22): All columns renamed to match contract
// - user_profiles: points→points_balance, total_points_earned→total_earned_from_gms
// - user_points_balances: base_points→points_balance, total_points→total_score
// - See supabase.generated.ts header for complete rename list
//
// ❌ FORBIDDEN: "blockchainPoints", "viralXP", "base_points"
// ✅ REQUIRED: Update all 4 layers when changing any points field

export type { Json, Database, Tables, TablesInsert, TablesUpdate, Enums, CompositeTypes } from './supabase.generated';
export { Constants } from './supabase.generated';
