module.exports = class Data1767252804780 {
    name = 'Data1767252804780'

    async up(db) {
        await db.query(`CREATE TABLE "stats_updated_event" ("id" character varying NOT NULL, "total_score" numeric NOT NULL, "level" integer NOT NULL, "rank_tier" integer NOT NULL, "multiplier" integer NOT NULL, "trigger_type" text NOT NULL, "trigger_amount" numeric NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "tx_hash" text NOT NULL, "user_id" character varying, CONSTRAINT "PK_83acbacbcac7a26e6499668fa68" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_24735f91e74c6d8b2472645580" ON "stats_updated_event" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_cb0ac048b3e09c72eea599691c" ON "stats_updated_event" ("trigger_type") `)
        await db.query(`CREATE INDEX "IDX_a293b28ae6be1701d666d7b96d" ON "stats_updated_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_bce30a1af2aca771f7581db329" ON "stats_updated_event" ("tx_hash") `)
        await db.query(`CREATE TABLE "level_up_event" ("id" character varying NOT NULL, "old_level" integer NOT NULL, "new_level" integer NOT NULL, "total_score" numeric NOT NULL, "level_gap" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "tx_hash" text NOT NULL, "user_id" character varying, CONSTRAINT "PK_7a623bbd7abdb5b7239faf6c4bc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4e1f26d265f740db98afcf6b47" ON "level_up_event" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_1f06c2359f276d1f1b61246ab6" ON "level_up_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_3041fa51fc3daf1e263a284f89" ON "level_up_event" ("tx_hash") `)
        await db.query(`CREATE TABLE "rank_up_event" ("id" character varying NOT NULL, "old_tier" integer NOT NULL, "new_tier" integer NOT NULL, "total_score" numeric NOT NULL, "tier_gap" integer NOT NULL, "new_multiplier" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "tx_hash" text NOT NULL, "user_id" character varying, CONSTRAINT "PK_3cc910cb51664a7fd93e7d24558" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1a16cab6c29aa846d330791daf" ON "rank_up_event" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_bbe4e8a47e9946aac80945a484" ON "rank_up_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_1d593bd468345056a231360288" ON "rank_up_event" ("tx_hash") `)
        
        // Add User columns with defaults for existing records
        await db.query(`ALTER TABLE "user" ADD "level" integer NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "rank_tier" integer NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "total_score" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "multiplier" integer NOT NULL DEFAULT 100`)
        await db.query(`ALTER TABLE "user" ADD "gm_points" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "viral_points" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "quest_points" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "guild_points" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "referral_points" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "xp_into_level" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "xp_to_next_level" numeric NOT NULL DEFAULT 100`)
        await db.query(`ALTER TABLE "user" ADD "points_into_tier" numeric NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "points_to_next_tier" numeric NOT NULL DEFAULT 1000`)
        await db.query(`ALTER TABLE "user" ADD "last_level_up_at" TIMESTAMP WITH TIME ZONE`)
        await db.query(`ALTER TABLE "user" ADD "last_rank_up_at" TIMESTAMP WITH TIME ZONE`)
        await db.query(`ALTER TABLE "user" ADD "total_level_ups" integer NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "user" ADD "total_rank_ups" integer NOT NULL DEFAULT 0`)
        
        // Add LeaderboardEntry columns with defaults
        await db.query(`ALTER TABLE "leaderboard_entry" ADD "level" integer NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "leaderboard_entry" ADD "rank_tier" integer NOT NULL DEFAULT 0`)
        await db.query(`ALTER TABLE "leaderboard_entry" ADD "multiplier" integer NOT NULL DEFAULT 100`)
        await db.query(`ALTER TABLE "leaderboard_entry" ADD "previous_rank" integer`)
        await db.query(`ALTER TABLE "leaderboard_entry" ADD "rank_change" integer`)
        await db.query(`CREATE INDEX "IDX_07e0e701989f1040fadbe54096" ON "user" ("level") `)
        await db.query(`CREATE INDEX "IDX_60f7f5e068ac5205e8d61fe5b1" ON "user" ("rank_tier") `)
        await db.query(`CREATE INDEX "IDX_80d462b64b72ab0371f798a642" ON "user" ("total_score") `)
        await db.query(`ALTER TABLE "stats_updated_event" ADD CONSTRAINT "FK_24735f91e74c6d8b2472645580a" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "level_up_event" ADD CONSTRAINT "FK_4e1f26d265f740db98afcf6b47b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "rank_up_event" ADD CONSTRAINT "FK_1a16cab6c29aa846d330791daf3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "stats_updated_event"`)
        await db.query(`DROP INDEX "public"."IDX_24735f91e74c6d8b2472645580"`)
        await db.query(`DROP INDEX "public"."IDX_cb0ac048b3e09c72eea599691c"`)
        await db.query(`DROP INDEX "public"."IDX_a293b28ae6be1701d666d7b96d"`)
        await db.query(`DROP INDEX "public"."IDX_bce30a1af2aca771f7581db329"`)
        await db.query(`DROP TABLE "level_up_event"`)
        await db.query(`DROP INDEX "public"."IDX_4e1f26d265f740db98afcf6b47"`)
        await db.query(`DROP INDEX "public"."IDX_1f06c2359f276d1f1b61246ab6"`)
        await db.query(`DROP INDEX "public"."IDX_3041fa51fc3daf1e263a284f89"`)
        await db.query(`DROP TABLE "rank_up_event"`)
        await db.query(`DROP INDEX "public"."IDX_1a16cab6c29aa846d330791daf"`)
        await db.query(`DROP INDEX "public"."IDX_bbe4e8a47e9946aac80945a484"`)
        await db.query(`DROP INDEX "public"."IDX_1d593bd468345056a231360288"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "level"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "rank_tier"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "total_score"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "multiplier"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "gm_points"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "viral_points"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "quest_points"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "guild_points"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "referral_points"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "xp_into_level"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "xp_to_next_level"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "points_into_tier"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "points_to_next_tier"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "last_level_up_at"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "last_rank_up_at"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "total_level_ups"`)
        await db.query(`ALTER TABLE "user" DROP COLUMN "total_rank_ups"`)
        await db.query(`ALTER TABLE "leaderboard_entry" DROP COLUMN "level"`)
        await db.query(`ALTER TABLE "leaderboard_entry" DROP COLUMN "rank_tier"`)
        await db.query(`ALTER TABLE "leaderboard_entry" DROP COLUMN "multiplier"`)
        await db.query(`ALTER TABLE "leaderboard_entry" DROP COLUMN "previous_rank"`)
        await db.query(`ALTER TABLE "leaderboard_entry" DROP COLUMN "rank_change"`)
        await db.query(`DROP INDEX "public"."IDX_07e0e701989f1040fadbe54096"`)
        await db.query(`DROP INDEX "public"."IDX_60f7f5e068ac5205e8d61fe5b1"`)
        await db.query(`DROP INDEX "public"."IDX_80d462b64b72ab0371f798a642"`)
        await db.query(`ALTER TABLE "stats_updated_event" DROP CONSTRAINT "FK_24735f91e74c6d8b2472645580a"`)
        await db.query(`ALTER TABLE "level_up_event" DROP CONSTRAINT "FK_4e1f26d265f740db98afcf6b47b"`)
        await db.query(`ALTER TABLE "rank_up_event" DROP CONSTRAINT "FK_1a16cab6c29aa846d330791daf3"`)
    }
}
