#!/bin/bash
# Complete Contract Redeployment Script
# Deploys GmeowCore with escrow fix + updates all configs

set -e

echo "🚀 Complete GmeowCore Redeployment"
echo "==================================="
echo ""

# Load environment
if [ -f .env.local ]; then
    export $(grep -v '^#' .env.local | grep -E 'ORACLE_PRIVATE_KEY|BASE_RPC' | xargs)
fi

if [ -z "$ORACLE_PRIVATE_KEY" ]; then
    echo "❌ ORACLE_PRIVATE_KEY not found in .env.local"
    exit 1
fi

ORACLE_ADDRESS=$(cast wallet address $ORACLE_PRIVATE_KEY)
BASE_RPC=${BASE_RPC:-"https://mainnet.base.org"}

echo "Oracle: $ORACLE_ADDRESS"
echo "Network: Base Mainnet"
echo ""

read -p "⚠️  This will deploy a NEW contract and UPDATE all configs. Continue? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

echo ""
echo "📦 Step 1: Building contracts..."
forge build

echo ""
echo "🚀 Step 2: Deploying GmeowCore..."
DEPLOY_OUTPUT=$(forge create contract/proxy/GmeowCore.sol:GmeowCore \
    --rpc-url $BASE_RPC \
    --private-key $ORACLE_PRIVATE_KEY \
    --verify \
    --verifier blockscout \
    --verifier-url https://base.blockscout.com/api \
    2>&1)

echo "$DEPLOY_OUTPUT"

# Extract contract address
CORE_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "Deployed to:" | awk '{print $3}')

if [ -z "$CORE_ADDRESS" ]; then
    echo "❌ Failed to deploy contract"
    exit 1
fi

echo ""
echo "✅ GmeowCore deployed: $CORE_ADDRESS"

# Get deployment block number
DEPLOY_BLOCK=$(cast receipt $(echo "$DEPLOY_OUTPUT" | grep "Transaction hash:" | awk '{print $3}') --rpc-url $BASE_RPC | grep "blockNumber" | awk '{print $2}')

echo "📍 Deployment block: $DEPLOY_BLOCK"

echo ""
echo "🔧 Step 3: Initializing contract..."
cast send $CORE_ADDRESS \
    "initialize(address)" $ORACLE_ADDRESS \
    --rpc-url $BASE_RPC \
    --private-key $ORACLE_PRIVATE_KEY

echo ""
echo "💰 Step 4: Depositing initial points (10,000)..."
cast send $CORE_ADDRESS \
    "depositTo(address,uint256)" $ORACLE_ADDRESS 10000 \
    --rpc-url $BASE_RPC \
    --private-key $ORACLE_PRIVATE_KEY

echo ""
echo "📝 Step 5: Updating ABI files..."

# Export ABI
forge inspect contract/proxy/GmeowCore.sol:GmeowCore abi > abi/GmeowCore.json

# Update GM_CONTRACT_ABI constant in codebase
ABI_CONTENT=$(cat abi/GmeowCore.json)

# Create temporary file with new ABI
cat > /tmp/new-abi.ts << 'EOF'
/**
 * GmeowCore Contract ABI
 * Auto-generated from forge inspect
 * Last updated: $(date)
 */
export const GM_CONTRACT_ABI = 
EOF

echo "$ABI_CONTENT" | jq -c '.' >> /tmp/new-abi.ts
echo " as const;" >> /tmp/new-abi.ts

# Backup old ABI
if [ -f "lib/contracts/abis/gmeow-core.ts" ]; then
    cp lib/contracts/abis/gmeow-core.ts lib/contracts/abis/gmeow-core.ts.backup
fi

# Copy new ABI
cp /tmp/new-abi.ts lib/contracts/abis/gmeow-core.ts

echo ""
echo "🔧 Step 6: Updating contract addresses..."

# Update .env.local
if grep -q "NEXT_PUBLIC_CORE_CONTRACT_ADDRESS=" .env.local; then
    sed -i.backup "s/NEXT_PUBLIC_CORE_CONTRACT_ADDRESS=.*/NEXT_PUBLIC_CORE_CONTRACT_ADDRESS=$CORE_ADDRESS/" .env.local
else
    echo "NEXT_PUBLIC_CORE_CONTRACT_ADDRESS=$CORE_ADDRESS" >> .env.local
fi

if grep -q "NEXT_PUBLIC_DEPLOYMENT_BLOCK=" .env.local; then
    sed -i.backup "s/NEXT_PUBLIC_DEPLOYMENT_BLOCK=.*/NEXT_PUBLIC_DEPLOYMENT_BLOCK=$DEPLOY_BLOCK/" .env.local
else
    echo "NEXT_PUBLIC_DEPLOYMENT_BLOCK=$DEPLOY_BLOCK" >> .env.local
fi

# Update config files
cat > config/contracts.ts << EOF
/**
 * Contract Addresses
 * Auto-generated by redeploy-complete.sh
 * Last updated: $(date)
 */

export const CONTRACTS = {
  CORE: '$CORE_ADDRESS' as const,
  DEPLOYMENT_BLOCK: $DEPLOY_BLOCK,
  CHAIN_ID: 8453, // Base Mainnet
} as const;

export const CORE_CONTRACT_ADDRESS = CONTRACTS.CORE;
export const DEPLOYMENT_BLOCK = CONTRACTS.DEPLOYMENT_BLOCK;
EOF

echo ""
echo "✅ Step 7: Verification on BaseScan..."
echo "Contract should be auto-verified on Blockscout"
echo "View at: https://base.blockscout.com/address/$CORE_ADDRESS"

echo ""
echo "📊 Step 8: Testing deployment..."

# Test contract is initialized
ORACLE_SIGNER=$(cast call $CORE_ADDRESS "oracleSigner()(address)" --rpc-url $BASE_RPC)
echo "Oracle signer: $ORACLE_SIGNER"

# Test points balance
POINTS_BALANCE=$(cast call $CORE_ADDRESS "pointsBalance(address)(uint256)" $ORACLE_ADDRESS --rpc-url $BASE_RPC)
echo "Oracle points: $POINTS_BALANCE (should be 10000)"

# Verify escrow fix is present (check if fixQuestEscrow exists)
QUEST_ESCROW_SIG=$(cast sig "fixQuestEscrow(uint256)")
echo "Contract has fixQuestEscrow: $QUEST_ESCROW_SIG"

echo ""
echo "=========================================="
echo "✅ DEPLOYMENT COMPLETE!"
echo "=========================================="
echo ""
echo "📝 Summary:"
echo "  Contract: $CORE_ADDRESS"
echo "  Block: $DEPLOY_BLOCK"
echo "  Oracle: $ORACLE_ADDRESS"
echo "  Points: $POINTS_BALANCE"
echo ""
echo "📋 Next Steps:"
echo "  1. Update Subsquid indexer:"
echo "     - Edit gmeow-indexer/src/main.ts"
echo "     - Set CORE_ADDRESS = '$CORE_ADDRESS'"
echo "     - Set FROM_BLOCK = $DEPLOY_BLOCK"
echo "     - Run: cd gmeow-indexer && sqd up && sqd migration:apply"
echo ""
echo "  2. Restart Next.js:"
echo "     - Kill current dev server"
echo "     - Run: pnpm dev"
echo ""
echo "  3. Test quest creation:"
echo "     - Visit http://localhost:3000/quests/create"
echo "     - Create a test quest"
echo "     - Verify escrow is set correctly"
echo ""
echo "  4. Verify on BaseScan:"
echo "     https://base.blockscout.com/address/$CORE_ADDRESS"
echo ""
echo "🔗 Updated Files:"
echo "  - .env.local (NEXT_PUBLIC_CORE_CONTRACT_ADDRESS)"
echo "  - config/contracts.ts"
echo "  - lib/contracts/abis/gmeow-core.ts"
echo "  - abi/GmeowCore.json"
echo ""
