#!/bin/bash

# Farcaster Manifest Signing Helper
# This script provides instructions and tools for signing the manifest

MANIFEST_PATH="public/.well-known/farcaster.json"
DOMAIN="gmeowhq.art"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔐 Farcaster Manifest Signing Helper"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Domain: $DOMAIN"
echo "Manifest: $MANIFEST_PATH"
echo ""

# Check if manifest exists
if [ ! -f "$MANIFEST_PATH" ]; then
    echo "❌ ERROR: Manifest file not found at $MANIFEST_PATH"
    exit 1
fi

# Check if manifest has placeholder values
if grep -q "PLACEHOLDER" "$MANIFEST_PATH"; then
    echo "⚠️  Status: UNSIGNED (contains placeholder values)"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  📋 Signing Instructions"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Option 1: Use Farcaster Manifest Tool (Recommended)"
    echo "─────────────────────────────────────────────────────────────"
    echo "1. Visit the Farcaster Miniapp Manifest Tool"
    echo "   (Check latest URL in Farcaster documentation)"
    echo ""
    echo "2. Enter your domain: $DOMAIN"
    echo ""
    echo "3. Click 'Claim Ownership' and follow the prompts"
    echo ""
    echo "4. Sign with your Farcaster custody address (via mobile)"
    echo ""
    echo "5. Copy the complete signed manifest"
    echo ""
    echo "6. Replace $MANIFEST_PATH with the signed version"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Option 2: Use Neynar Mini App Manifest Tool"
    echo "─────────────────────────────────────────────────────────────"
    echo "Visit: https://docs.neynar.com/docs/convert-web-app-to-mini-app"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Option 3: Use @farcaster/miniapp-sdk"
    echo "─────────────────────────────────────────────────────────────"
    echo "import { signManifest } from '@farcaster/miniapp-sdk'"
    echo ""
    echo "const signature = await signManifest({"
    echo "  domain: '$DOMAIN'"
    echo "})"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📖 For detailed instructions, see: MANIFEST_SETUP.md"
    echo ""
else
    echo "✅ Status: SIGNED (no placeholder values detected)"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  🎉 Next Steps"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "1. Validate the manifest:"
    echo "   node scripts/validate-manifest.js"
    echo ""
    echo "2. Test locally:"
    echo "   npm run dev"
    echo "   curl http://localhost:3000/.well-known/farcaster.json"
    echo ""
    echo "3. Deploy to production:"
    echo "   vercel --prod"
    echo ""
    echo "4. Verify in Warpcast:"
    echo "   Settings > Developer Tools > Domains"
    echo "   Enter: $DOMAIN"
    echo "   Click: 'Check domain status'"
    echo ""
    echo "5. Test the miniapp:"
    echo "   Visit: https://$DOMAIN"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Additional Resources:"
echo "   • MANIFEST_SETUP.md - Complete setup guide"
echo "   • MANIFEST_REGENERATION_SUMMARY.md - Change summary"
echo "   • scripts/validate-manifest.js - Validation tool"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
