module.exports = {
  id: 'gmeowbased_visual_regression',
  viewports: [
    {
      label: 'phone',
      width: 375,
      height: 812,
    },
    {
      label: 'tablet',
      width: 768,
      height: 1024,
    },
    {
      label: 'desktop',
      width: 1920,
      height: 1080,
    },
  ],
  onBeforeScript: 'puppet/onBefore.js',
  onReadyScript: 'puppet/onReady.js',
  scenarios: [
    {
      label: 'Leaderboard - Light Mode',
      url: 'http://localhost:3000/leaderboard',
      referenceUrl: '',
      readyEvent: '',
      readySelector: '.leaderboard-table',
      delay: 2000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: '',
      clickSelector: '',
      postInteractionWait: 0,
      selectors: ['document'],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
    },
    {
      label: 'Leaderboard - Dark Mode',
      url: 'http://localhost:3000/leaderboard',
      referenceUrl: '',
      readyEvent: '',
      readySelector: '.leaderboard-table',
      delay: 2000,
      hideSelectors: [],
      removeSelectors: [],
      onBeforeScript: 'puppet/darkMode.js',
      selectors: ['document'],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
    },
    {
      label: 'Leaderboard - Mobile Card View',
      url: 'http://localhost:3000/leaderboard',
      readySelector: '.mobile-card',
      delay: 2000,
      selectors: ['.mobile-card'],
      viewports: [
        {
          label: 'phone',
          width: 375,
          height: 812,
        },
      ],
      misMatchThreshold: 0.1,
    },
    {
      label: 'Leaderboard - Table Header',
      url: 'http://localhost:3000/leaderboard',
      readySelector: 'table thead',
      delay: 1000,
      selectors: ['table thead'],
      misMatchThreshold: 0.05,
    },
    {
      label: 'Leaderboard - Event Badges',
      url: 'http://localhost:3000/leaderboard',
      readySelector: '.roster-chip',
      delay: 1500,
      selectors: ['.roster-chip'],
      misMatchThreshold: 0.05,
    },
    {
      label: 'Leaderboard - Pagination',
      url: 'http://localhost:3000/leaderboard',
      readySelector: 'nav[aria-label="pagination"]',
      delay: 1000,
      selectors: ['nav[aria-label="pagination"]'],
      misMatchThreshold: 0.05,
    },
  ],
  paths: {
    bitmaps_reference: 'backstop_data/bitmaps_reference',
    bitmaps_test: 'backstop_data/bitmaps_test',
    engine_scripts: 'backstop_data/engine_scripts',
    html_report: 'backstop_data/html_report',
    ci_report: 'backstop_data/ci_report',
  },
  report: ['browser', 'json'],
  engine: 'puppeteer',
  engineOptions: {
    args: ['--no-sandbox'],
  },
  asyncCaptureLimit: 5,
  asyncCompareLimit: 50,
  debug: false,
  debugWindow: false,
};
