#!/bin/bash
# Check GitHub Actions secrets status via Copilot MCP
echo "📋 GitHub Secrets Status Check"
echo "==============================="
echo ""
echo "Since GitHub CLI isn't installed, I'll help you check via MCP."
echo ""
echo "Required secrets for your workflows:"
echo ""
echo "🔴 CRITICAL (All workflows):"
echo "  - SUPABASE_URL"
echo "  - SUPABASE_SERVICE_ROLE_KEY" 
echo "  - SUPABASE_ANON_KEY"
echo "  - NEYNAR_API_KEY"
echo ""
echo "🟡 IMPORTANT (Blockchain):"
echo "  - RPC_BASE"
echo "  - RPC_OP"
echo "  - RPC_CELO"
echo "  - RPC_UNICHAIN"
echo "  - RPC_INK"
echo ""
echo "🟢 OPTIONAL (Badge minting):"
echo "  - MINTER_PRIVATE_KEY"
echo ""
echo "📊 To check which secrets are configured:"
echo "   Ask Copilot: 'Check my GitHub secrets status'"
echo ""
echo "➕ To add a secret:"
echo "   Ask Copilot: 'Add [SECRET_NAME] to GitHub secrets'"
echo ""
echo "🧪 To test workflows:"
echo "   Ask Copilot: 'Test the badge-minting workflow'"
echo ""
