#!/bin/bash
# Deploy Gmeow contracts - Auto-updated with rich verification
# Generated by universal updater

set -e

# Extract chain info from filename
SCRIPT_NAME=$(basename "$0")
CHAIN_NAME=${SCRIPT_NAME#deploy-}
CHAIN_NAME=${CHAIN_NAME%.sh}

echo "🚀 Deploying to $CHAIN_NAME..."
echo "======================="

# Configuration
RPC="https://rpc-gel.inkonchain.com"
ORACLE_ADDRESS=$(cast wallet address $PRIVATE_KEY)
PRIVATE_KEY=$(grep ORACLE_PRIVATE_KEY .env.local | cut -d= -f2)

# API Keys for Verification (Optional)
# Add these to your .env.local file:
# ETHERSCAN_API_KEY=your_etherscan_api_key
# CHAIN_SPECIFIC_API_KEY=your_chain_specific_api_key (if different)
ETHERSCAN_API_KEY=$(grep ETHERSCAN_API_KEY .env.local 2>/dev/null | cut -d= -f2 || echo "")
CHAIN_API_KEY=$(grep INK_API_KEY .env.local 2>/dev/null | cut -d= -f2 || echo "$ETHERSCAN_API_KEY")

# Function to extract contract address from forge output
extract_contract_address() {
    local output="$1"
    echo "$output" | grep "Deployed to:" | tail -1 | awk '{print $3}'
}

# Check balance
echo "📊 Checking balance..."
BALANCE=$(cast balance $ORACLE_ADDRESS --rpc-url $RPC)
echo "Balance: $(cast --from-wei $BALANCE) ETH"

if [ "$BALANCE" = "0" ]; then
  echo "❌ No ETH balance on Arbitrum!"
  exit 1
fi

# Deploy Core
echo ""
echo "🏗️ Step 1/8: Deploying Core..."
CORE_DEPLOY_OUTPUT=$(forge create contract/GmeowCoreStandalone.sol:GmeowCore \
  --broadcast \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY \
  --constructor-args $ORACLE_ADDRESS 2>&1)

echo "$CORE_DEPLOY_OUTPUT"
CORE_ADDRESS=$(extract_contract_address "$CORE_DEPLOY_OUTPUT")

if [ -z "$CORE_ADDRESS" ]; then
  echo "❌ Failed to extract Core contract address"
  echo "Please manually enter the Core contract address:"
  read -r CORE_ADDRESS
fi

echo "✅ Core Address: $CORE_ADDRESS"

# Deploy Guild
echo ""
echo "🏗️ Step 2/8: Deploying Guild..."
GUILD_DEPLOY_OUTPUT=$(forge create contract/GmeowGuildStandalone.sol:GmeowGuildStandalone \
  --broadcast \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY \
  --constructor-args $CORE_ADDRESS 2>&1)

echo "$GUILD_DEPLOY_OUTPUT"
GUILD_ADDRESS=$(extract_contract_address "$GUILD_DEPLOY_OUTPUT")

if [ -z "$GUILD_ADDRESS" ]; then
  echo "❌ Failed to extract Guild contract address"
  echo "Please manually enter the Guild contract address:"
  read -r GUILD_ADDRESS
fi

echo "✅ Guild Address: $GUILD_ADDRESS"

# Deploy NFT
echo ""
echo "🏗️ Step 3/8: Deploying NFT..."
NFT_DEPLOY_OUTPUT=$(forge create contract/GmeowNFTStandalone.sol:GmeowNFTStandalone \
  --broadcast \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY \
  --constructor-args $CORE_ADDRESS "Gmeow Adventure NFT" "GMEOW" "https://api.gmeowhq.art/nft/" 2>&1)

echo "$NFT_DEPLOY_OUTPUT"
NFT_ADDRESS=$(extract_contract_address "$NFT_DEPLOY_OUTPUT")

if [ -z "$NFT_ADDRESS" ]; then
  echo "❌ Failed to extract NFT contract address"
  echo "Please manually enter the NFT contract address:"
  read -r NFT_ADDRESS
fi

echo "✅ NFT Address: $NFT_ADDRESS"

# Deploy Proxy
echo ""
echo "🏗️ Step 4/8: Deploying Proxy..."
PROXY_DEPLOY_OUTPUT=$(forge create contract/proxy/GmeowProxy.sol:GmeowProxy \
  --broadcast \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY \
  --constructor-args $CORE_ADDRESS $GUILD_ADDRESS $NFT_ADDRESS 2>&1)

echo "$PROXY_DEPLOY_OUTPUT"
PROXY_ADDRESS=$(extract_contract_address "$PROXY_DEPLOY_OUTPUT")

if [ -z "$PROXY_ADDRESS" ]; then
  echo "❌ Failed to extract Proxy contract address"
  echo "Please manually enter the Proxy contract address:"
  read -r PROXY_ADDRESS
fi

echo "✅ Proxy Address: $PROXY_ADDRESS"

# Link Guild to Core
echo ""
echo "🔗 Step 5/8: Linking Guild to Core..."
cast send $CORE_ADDRESS \
  "setGuildContract(address)" \
  $GUILD_ADDRESS \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY

# Link NFT to Core
echo ""
echo "🔗 Step 6/8: Linking NFT to Core..."
cast send $CORE_ADDRESS \
  "setNFTContractAddress(address)" \
  $NFT_ADDRESS \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY

# Initialize Proxy
echo ""
echo "🚀 Step 7/8: Initializing Proxy..."
cast send $PROXY_ADDRESS \
  "initialize()" \
  --rpc-url $RPC \
  --private-key $PRIVATE_KEY

# Test deployment
echo ""
echo "🧪 Step 8/9: Testing deployment..."
echo -n "Oracle Signer: "
cast call $CORE_ADDRESS "oracleSigner()" --rpc-url $RPC
echo -n "Guild Contract: "
cast call $CORE_ADDRESS "guildContract()" --rpc-url $RPC
echo -n "NFT Contract: "
cast call $CORE_ADDRESS "nftContractAddress()" --rpc-url $RPC
echo -n "GM Point Reward: "
cast call $CORE_ADDRESS "gmPointReward()" --rpc-url $RPC | cast --to-dec
echo -n "Proxy Core Address: "
cast call $PROXY_ADDRESS "coreContract()" --rpc-url $RPC
echo -n "Proxy Guild Address: "
cast call $PROXY_ADDRESS "guildContract()" --rpc-url $RPC
echo -n "Proxy NFT Address: "
cast call $PROXY_ADDRESS "nftContract()" --rpc-url $RPC

echo ""
echo "✅ All contract links verified!"

# Rich verification section
echo ""
echo "🔍 Step 9/9: Contract Verification..."

# Function to verify contract on multiple explorers
verify_contract_multi() {
    local address=$1
    local contract_path=$2
    local constructor_args=$3
    local contract_name=$4
    local chain_id=$5
    
    echo "🔍 Verifying $contract_name ($address)..."
    
    local verification_success=false
    
    # Try chain-specific API key (primary)
    if [ ! -z "$CHAIN_API_KEY" ]; then
        echo "  📍 Verifying on Ink Explorer..."
        if forge verify-contract \
            $address \
            $contract_path \
            --chain-id $chain_id \
            --constructor-args $constructor_args \
            --etherscan-api-key $CHAIN_API_KEY \
            --watch 2>/dev/null; then
            echo "  ✅ Ink Explorer verification successful"
            verification_success=true
        else
            echo "  ❌ Ink Explorer verification failed"
        fi
    fi
    
    # Try regular Etherscan API (fallback)
    if [ "$verification_success" = false ] && [ ! -z "$ETHERSCAN_API_KEY" ]; then
        echo "  📍 Trying Etherscan API..."
        if forge verify-contract \
            $address \
            $contract_path \
            --chain-id $chain_id \
            --constructor-args $constructor_args \
            --etherscan-api-key $ETHERSCAN_API_KEY \
            --watch 2>/dev/null; then
            echo "  ✅ Etherscan verification successful"
            verification_success=true
        else
            echo "  ❌ Etherscan verification failed"
        fi
    fi
    
    # Try without API key (public endpoint)
    if [ "$verification_success" = false ]; then
        echo "  📍 Trying public verification endpoint..."
        if forge verify-contract \
            $address \
            $contract_path \
            --chain-id $chain_id \
            --constructor-args $constructor_args \
            --watch 2>/dev/null; then
            echo "  ✅ Public endpoint verification successful"
            verification_success=true
        else
            echo "  ❌ Public endpoint verification failed"
        fi
    fi
    
    if [ "$verification_success" = false ]; then
        echo "  ⚠️  All verification attempts failed for $contract_name"
        echo "      You can manually verify at: https://explorer.inkonchain.com/verifyContract"
        echo "      Contract Address: $address"
    fi
    
    echo ""
}

# Check if any API keys are available
if [ ! -z "$CHAIN_API_KEY" ] || [ ! -z "$ETHERSCAN_API_KEY" ]; then
    echo "🔑 Using API keys for verification:"
    [ ! -z "$CHAIN_API_KEY" ] && echo "  ✅ Ink Explorer API Key: ${CHAIN_API_KEY:0:8}..."
    [ ! -z "$ETHERSCAN_API_KEY" ] && echo "  ✅ Etherscan API Key: ${ETHERSCAN_API_KEY:0:8}..."
    echo ""
    
    # Verify all contracts
    verify_contract_multi \
        "$CORE_ADDRESS" \
        "contract/GmeowCoreStandalone.sol:GmeowCore" \
        "$(cast abi-encode "constructor(address)" $ORACLE_ADDRESS)" \
        "Core" \
        "57073"
    
    verify_contract_multi \
        "$GUILD_ADDRESS" \
        "contract/GmeowGuildStandalone.sol:GmeowGuildStandalone" \
        "$(cast abi-encode "constructor(address)" $CORE_ADDRESS)" \
        "Guild" \
        "57073"
    
    verify_contract_multi \
        "$NFT_ADDRESS" \
        "contract/GmeowNFTStandalone.sol:GmeowNFTStandalone" \
        "$(cast abi-encode "constructor(address,string,string,string)" $CORE_ADDRESS "Gmeow Adventure NFT" "GMEOW" "https://api.gmeowhq.art/nft/")" \
        "NFT" \
        "57073"
    
    verify_contract_multi \
        "$PROXY_ADDRESS" \
        "contract/proxy/GmeowProxy.sol:GmeowProxy" \
        "$(cast abi-encode "constructor(address,address,address)" $CORE_ADDRESS $GUILD_ADDRESS $NFT_ADDRESS)" \
        "Proxy" \
        "57073"
        
    echo "🎯 Verification Summary:"
    echo "   View all contracts on Ink Explorer: https://explorer.inkonchain.com"
    echo "   Core:  https://explorer.inkonchain.com/address/$CORE_ADDRESS"
    echo "   Guild: https://explorer.inkonchain.com/address/$GUILD_ADDRESS"
    echo "   NFT:   https://explorer.inkonchain.com/address/$NFT_ADDRESS"
    echo "   Proxy: https://explorer.inkonchain.com/address/$PROXY_ADDRESS"
    
else
    echo "⚠️  No API keys found for verification"
    echo ""
    echo "📝 To enable automatic verification, add to your .env.local:"
    echo "   ETHERSCAN_API_KEY=your_etherscan_api_key"
    echo "   INK_API_KEY=your_chain_specific_api_key  # (optional, uses ETHERSCAN_API_KEY if not set)"
    echo ""
    echo "🔗 Manual verification links:"
    echo "   Ink Explorer: https://explorer.inkonchain.com/verifyContract"
    echo "   Core:  $CORE_ADDRESS"
    echo "   Guild: $GUILD_ADDRESS"
    echo "   NFT:   $NFT_ADDRESS" 
    echo "   Proxy: $PROXY_ADDRESS"
fi

# Save deployment record
echo ""
echo "💾 Saving deployment record..."
mkdir -p deployment-records
cat > deployment-records/${CHAIN_NAME}-deployment.json << EOF
{
  "chainId": 57073,
  "chainName": "$CHAIN_NAME",
  "network": "Ink Mainnet",
  "deploymentDate": "$(date -Iseconds)",
  "contracts": {
    "core": "$CORE_ADDRESS",
    "guild": "$GUILD_ADDRESS",
    "nft": "$NFT_ADDRESS",
    "proxy": "$PROXY_ADDRESS"
  },
  "rpcUrl": "$RPC",
  "explorer": "https://explorer.inkonchain.com"
}
EOF

echo ""
echo "🎉 $CHAIN_NAME deployment complete!"
echo "📄 Deployment record saved: deployment-records/${CHAIN_NAME}-deployment.json"
echo ""
echo "📋 Contract Addresses:"
echo "   Core:  $CORE_ADDRESS"
echo "   Guild: $GUILD_ADDRESS"
echo "   NFT:   $NFT_ADDRESS"
echo "   Proxy: $PROXY_ADDRESS"
echo ""
echo "🌐 View on Ink Explorer:"
echo "   https://explorer.inkonchain.com/address/$PROXY_ADDRESS"
